{
 "title": "DLINK",
 "description": "Dashboard for OpenWRT routers with installed lua scripts.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "WAN Connected",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_device_hardware_info" }
   ]
  },
  {
   "title": "Devices on Network",
   "type": "gauge",
   "description": "sum of all devices",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_network_client_interface{instance=\"router:9731\", job=\"servers\", Type!=\"OFFLINE\"})",
     "legendFormat": "{{Type}}"
    }
   ]
  },
  {
   "title": "LAN on Network",
   "type": "gauge",
   "description": "sum of all devices",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_network_client_interface{instance=\"router:9731\", job=\"servers\", Type=\"LAN\"})",
     "legendFormat": "{{Type}}"
    }
   ]
  },
  {
   "title": "WIFI on Network",
   "type": "gauge",
   "description": "sum of all devices",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_network_client_interface{instance=\"router:9731\", job=\"servers\", Type=~\"WiFi.*\"})",
     "legendFormat": "{{Type}}"
    }
   ]
  },
  {
   "title": "WIFI %",
   "type": "gauge",
   "description": "sum of all devices",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_network_client_interface{instance=\"router:9731\", job=\"servers\", Type=~\"WiFi.*\"})/sum(node_network_client_interface{instance=\"router:9731\", job=\"servers\", Type!=\"OFFLINE\"})",
     "legendFormat": "{{Type}}"
    }
   ]
  },
  {
   "title": "LAN %",
   "type": "gauge",
   "description": "sum of all devices",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_network_client_interface{instance=\"router:9731\", job=\"servers\", Type=~\"LAN\"})/sum(node_network_client_interface{instance=\"router:9731\", job=\"servers\", Type!=\"OFFLINE\"})",
     "legendFormat": "{{Type}}"
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=~\"router:9731\",job=~\"router\"} - node_memory_SwapFree_bytes{instance=~\"router:9731\",job=~\"router\"}) / (node_memory_SwapTotal_bytes{instance=~\"router:9731\",job=~\"router\"} )) * 100"
    }
   ]
  },
  {
   "title": "Used Root FS",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"router:9731\",job=~\"router\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"router:9731\",job=~\"router\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_device_hardware_info", "legendFormat": "{{customer_version}}" }
   ]
  },
  {
   "title": "Hardware Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_device_hardware_info", "legendFormat": "{{hardware_version}}" }
   ]
  },
  {
   "title": "Firmware",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_device_hardware_info", "legendFormat": "{{software_version}}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_device_hardware_info", "legendFormat": "{{hardware_version}}" }
   ]
  },
  {
   "title": "Total Network Traffic",
   "type": "stat",
   "description": "Total network traffic",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "(sum(node_network_transmit_bytes_total{instance=~\"router:9731\",job=~\"router\"}) + sum(node_network_receive_bytes_total{instance=~\"router:9731\",job=~\"router\"}))"
    }
   ]
  },
  {
   "title": "Total WAN Traffic",
   "type": "stat",
   "description": "Total network traffic",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "(sum(node_network_transmit_bytes_total{instance=~\"router:9731\",device=\"WAN\", job=~\"router\"}) + sum(node_network_receive_bytes_total{instance=~\"router:9731\",device=\"WAN\", job=~\"router\"}))"
    }
   ]
  },
  {
   "title": "Total LAN Traffic",
   "type": "stat",
   "description": "Total network traffic",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "(sum(node_network_transmit_bytes_total{instance=~\"router:9731\",device!=\"WAN\", job=~\"router\"}) + sum(node_network_receive_bytes_total{instance=~\"router:9731\",device!=\"WAN\", job=~\"router\"}))"
    }
   ]
  },
  {
   "title": "Total RootFS",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"router:9731\",job=~\"router\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "CPU Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Basic",
     "type": "graph",
     "description": "Basic CPU info",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"router:9731\",job=~\"router\"}[5m])) * 100",
       "legendFormat": "Busy System"
      },
      {
       "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=~\"router:9731\",job=~\"router\"}[5m])) * 100",
       "legendFormat": "Busy User"
      },
      {
       "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"router:9731\",job=~\"router\"}[5m])) * 100",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"router:9731\",job=~\"router\"}[5m])) * 100",
       "legendFormat": "Busy IRQs"
      },
      {
       "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"router:9731\",job=~\"router\"}[5m])) * 100",
       "legendFormat": "Busy Other"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"router:9731\",job=~\"router\"}[5m])) * 100",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Memory Basic",
     "type": "graph",
     "description": "Basic memory usage",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"router:9731\",job=~\"router\"} - node_memory_MemFree_bytes{instance=~\"router:9731\",job=~\"router\"} - (node_memory_Cached_bytes{instance=~\"router:9731\",job=~\"router\"} + node_memory_Buffers_bytes{instance=~\"router:9731\",job=~\"router\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~\"router:9731\",job=~\"router\"} + node_memory_Buffers_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "RAM Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=~\"router:9731\",job=~\"router\"} - node_memory_SwapFree_bytes{instance=~\"router:9731\",job=~\"router\"})",
       "legendFormat": "SWAP Used"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short", "label": "Percentage" }
     ],
     "targets": [
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"router:9731\",job=~\"router\"}[5m])) * 100",
       "legendFormat": "System - Processes executing in kernel mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='user',instance=~\"router:9731\",job=~\"router\"}[5m])) * 100",
       "legendFormat": "User - Normal processes executing in user mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='nice',instance=~\"router:9731\",job=~\"router\"}[5m])) * 100",
       "legendFormat": "Nice - Niced processes executing in user mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"router:9731\",job=~\"router\"}[5m])) * 100",
       "legendFormat": "Idle - Waiting for something to happen"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"router:9731\",job=~\"router\"}[5m])) * 100",
       "legendFormat": "Iowait - Waiting for I/O to complete"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='irq',instance=~\"router:9731\",job=~\"router\"}[5m])) * 100",
       "legendFormat": "Irq - Servicing interrupts"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='softirq',instance=~\"router:9731\",job=~\"router\"}[5m])) * 100",
       "legendFormat": "Softirq - Servicing softirqs"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='steal',instance=~\"router:9731\",job=~\"router\"}[5m])) * 100",
       "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='guest',instance=~\"router:9731\",job=~\"router\"}[5m])) * 100",
       "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
      }
     ]
    },
    {
     "title": "Memory Stack",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"router:9731\",job=~\"router\"} - node_memory_MemFree_bytes{instance=~\"router:9731\",job=~\"router\"} - node_memory_Buffers_bytes{instance=~\"router:9731\",job=~\"router\"} - node_memory_Cached_bytes{instance=~\"router:9731\",job=~\"router\"} - node_memory_Slab_bytes{instance=~\"router:9731\",job=~\"router\"} - node_memory_PageTables_bytes{instance=~\"router:9731\",job=~\"router\"} - node_memory_SwapCached_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "Apps - Memory used by user-space applications"
      },
      {
       "expr": "node_memory_PageTables_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
      },
      {
       "expr": "node_memory_SwapCached_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
      },
      {
       "expr": "node_memory_Slab_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "Cache - Parked file data (file content) cache"
      },
      {
       "expr": "node_memory_Buffers_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "Unused - Free memory unasigned"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=~\"router:9731\",job=~\"router\"} - node_memory_SwapFree_bytes{instance=~\"router:9731\",job=~\"router\"})",
       "legendFormat": "Swap - Swap space used"
      },
      {
       "expr": "node_memory_HardwareCorrupted_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "Harware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Detail Meminfo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Active / Inactive",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Inactive_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "Inactive - Memory which has been less recently used.  It is more eligible to be reclaimed for other purposes"
      },
      {
       "expr": "node_memory_Active_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "Active - Memory that has been used more recently and usually not reclaimed unless absolutely necessary"
      }
     ]
    },
    {
     "title": "Memory Commited",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Committed_AS_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "Committed_AS - Amount of memory presently allocated on the system"
      },
      {
       "expr": "node_memory_CommitLimit_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "CommitLimit - Amount of  memory currently available to be allocated on the system"
      }
     ]
    },
    {
     "title": "Memory Active / Inactive Detail",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Inactive_file_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "Inactive_file - File-backed memory on inactive LRU list"
      },
      {
       "expr": "node_memory_Inactive_anon_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "Inactive_anon - Anonymous and swap cache on inactive LRU list, including tmpfs (shmem)"
      },
      {
       "expr": "node_memory_Active_file_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "Active_file - File-backed memory on active LRU list"
      },
      {
       "expr": "node_memory_Active_anon_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "Active_anon - Anonymous and swap cache on active least-recently-used (LRU) list, including tmpfs"
      }
     ]
    },
    {
     "title": "Memory Writeback and Dirty",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Writeback_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "Writeback - Memory which is actively being written back to disk"
      },
      {
       "expr": "node_memory_WritebackTmp_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "WritebackTmp - Memory used by FUSE for temporary writeback buffers"
      },
      {
       "expr": "node_memory_Dirty_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "Dirty - Memory which is waiting to get written back to the disk"
      }
     ]
    },
    {
     "title": "Memory Shared and Mapped",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Mapped_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "Mapped - Used memory in mapped pages files which have been mmaped, such as libraries"
      },
      {
       "expr": "node_memory_Shmem_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "Shmem - Used shared memory (shared between several processes, thus including RAM disks)"
      }
     ]
    },
    {
     "title": "Memory Slab",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 64 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_SUnreclaim_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "SUnreclaim - Part of Slab, that cannot be reclaimed on memory pressure"
      },
      {
       "expr": "node_memory_SReclaimable_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "SReclaimable - Part of Slab, that might be reclaimed, such as caches"
      }
     ]
    },
    {
     "title": "Memory Vmalloc",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_VmallocChunk_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "VmallocChunk - Largest contigious block of vmalloc area which is free"
      },
      {
       "expr": "node_memory_VmallocTotal_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "VmallocTotal - Total size of vmalloc memory area"
      },
      {
       "expr": "node_memory_VmallocUsed_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "VmallocUsed - Amount of vmalloc area which is used"
      }
     ]
    },
    {
     "title": "Memory Bounce",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 74 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Bounce_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "Bounce - Memory used for block device bounce buffers"
      }
     ]
    },
    {
     "title": "Memory Anonymous",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_AnonHugePages_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "AnonHugePages - Memory in anonymous huge pages"
      },
      {
       "expr": "node_memory_AnonPages_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "AnonPages - Memory in user pages not backed by files"
      }
     ]
    },
    {
     "title": "Memory Kernel",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 84 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_KernelStack_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "KernelStack - Kernel memory stack. This is not reclaimable"
      }
     ]
    },
    {
     "title": "Memory NFS",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_NFS_Unstable_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "NFS Unstable - Memory in NFS pages sent to the server, but not yet commited to the storage"
      }
     ]
    },
    {
     "title": "Memory Unevictable and MLocked",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 94 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Unevictable_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "Unevictable - Amount of unevictable memory that can't be swapped out for a variety of reasons"
      },
      {
       "expr": "node_memory_Mlocked_bytes{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "MLocked - Size of pages locked to memory using the mlock() system call"
      }
     ]
    }
   ]
  },
  {
   "title": "System Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Context Switches / Interrupts",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_context_switches_total{instance=~\"router:9731\",job=~\"router\"}[5m])",
       "legendFormat": "Context switches"
      },
      {
       "expr": "irate(node_intr_total{instance=~\"router:9731\",job=~\"router\"}[5m])",
       "legendFormat": "Interrupts"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "Load" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "node_load5{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "node_load15{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "Load 15m"
      }
     ]
    },
    {
     "title": "Processes  Forks",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short", "label": "Forks / sec" }
     ],
     "targets": [
      {
       "expr": "irate(node_forks_total{instance=~\"router:9731\",job=~\"router\"}[5m])",
       "legendFormat": "Processes forks second"
      }
     ]
    },
    {
     "title": "File Descriptor",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short", "label": "Files" }
     ],
     "targets": [
      {
       "expr": "node_filefd_maximum{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "Max open files"
      },
      {
       "expr": "node_filefd_allocated{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "Open files"
      }
     ]
    }
   ]
  },
  {
   "title": "WiFi",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Wifi Stations",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(wifi_stations)" }
     ]
    },
    {
     "title": "wlan0 quality",
     "type": "gauge",
     "description": "Non available RAM memory",
     "gridPos": { "h": 7, "w": 3, "x": 3, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wifi_network_quality{instance=~\"router:9731\",job=~\"router\",ifname=\"wlan0\"}"
      }
     ]
    },
    {
     "title": "wlan0-1 quality",
     "type": "gauge",
     "description": "Non available RAM memory",
     "gridPos": { "h": 7, "w": 3, "x": 6, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wifi_network_quality{instance=~\"router:9731\",job=~\"router\",ifname=\"wlan0-1\"}"
      }
     ]
    },
    {
     "title": "wlan1 quality",
     "type": "gauge",
     "description": "Non available RAM memory",
     "gridPos": { "h": 7, "w": 3, "x": 9, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wifi_network_quality{instance=~\"router:9731\",job=~\"router\",ifname=\"wlan1\"}"
      }
     ]
    },
    {
     "title": "WiFi Network Noise",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "dBm" }
     ],
     "targets": [
      {
       "expr": "wifi_network_noise_dbm{instance=~\"router:9731\",job=~\"router\"}"
      }
     ]
    },
    {
     "title": "WiFi Stations",
     "type": "graph",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wifi_stations{instance=~\"router:9731\",job=~\"router\"}"
      }
     ]
    },
    {
     "title": "WiFi Bitrate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "Mbits" }
     ],
     "targets": [
      {
       "expr": "wifi_network_bitrate{instance=~\"router:9731\",job=~\"router\"}/1024",
       "legendFormat": "{{ifname}}"
      }
     ]
    },
    {
     "title": "WiFi Network Quality",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "wifi_network_quality{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "{{ifname}}"
      }
     ]
    },
    {
     "title": "WiFi Station Expected Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "Mbits" }
     ],
     "targets": [
      {
       "expr": "wifi_station_expected_throughput_kilobits_per_second{instance=~\"router:9731\",job=~\"router\"}/1024",
       "legendFormat": "{{mac}} # {{ifname}}"
      }
     ]
    },
    {
     "title": "WiFi Station Signal",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "dBm" }
     ],
     "targets": [
      {
       "expr": "wifi_station_signal_dbm{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "{{mac}} # {{ifname}}"
      }
     ]
    },
    {
     "title": "WiFi Station inactive",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "wifi_station_inactive_milliseconds{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "{{mac}} # {{ifname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Transmit Bytes Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{instance=~\"router:9731\",job=~\"router\"}/1024/1024",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Receive Bytes Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{instance=~\"router:9731\",job=~\"router\"}/1024/1024",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic by Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"router:9731\",job=~\"router\"}[5m])/1024",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"router:9731\",job=~\"router\"}[5m])/1024",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic by Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"router:9731\",job=~\"router\", device!=\"WAN\"}[5m])/1024",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"router:9731\",job=~\"router\",device!=\"WAN\"}[5m])/1024",
     "legendFormat": "{{device}} - Transmit"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"skull:9100\",job=~\"router\",device!=\"WAN\", device=\"eno1\"}[5m])/1024",
     "legendFormat": "Skull  - Transmit"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"skull:9100\",job=~\"router\",device!=\"WAN\", device=\"eno1\"}[5m])/1024",
     "legendFormat": "Skull  - Received"
    }
   ]
  },
  {
   "title": "Transmit Packets Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_network_transmit_packets_total{instance=~\"router:9731\",job=~\"router\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Receive Packets Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_network_receive_packets_total{instance=~\"router:9731\",job=~\"router\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Top NAT Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "topk(15, node_nat_traffic{instance=~\"router:9731\",job=~\"router\"}/1024/1024)",
     "legendFormat": "Dest= {{dest}} # Source= {{src}}"
    }
   ]
  },
  {
   "title": "Network Traffic Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Traffic Drop",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_drop_total{instance=~\"router:9731\",job=~\"router\"}[5m])",
     "legendFormat": "{{device}} - Receive drop"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{instance=~\"router:9731\",job=~\"router\"}[5m])",
     "legendFormat": "{{device}} - Transmit drop"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total{instance=~\"router:9731\",job=~\"router\"}[5m])",
     "legendFormat": "{{device}} - Receive errors"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=~\"router:9731\",job=~\"router\"}[5m])",
     "legendFormat": "{{device}} - Rransmit errors"
    }
   ]
  },
  {
   "title": "Network Traffic Multicast",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_multicast_total{instance=~\"router:9731\",job=~\"router\"}[5m])",
     "legendFormat": "{{device}} - Receive multicast"
    }
   ]
  },
  {
   "title": "Network Traffic Compressed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_compressed_total{instance=~\"router:9731\",job=~\"router\"}[5m])",
     "legendFormat": "{{device}} - Receive compressed"
    },
    {
     "expr": "irate(node_network_transmit_compressed_total{instance=~\"router:9731\",job=~\"router\"}[5m])",
     "legendFormat": "{{device}} - Transmit compressed"
    }
   ]
  },
  {
   "title": "Network Traffic Frame",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_frame_total{instance=~\"router:9731\",job=~\"router\"}[5m])",
     "legendFormat": "{{device}} - Receive frame"
    }
   ]
  },
  {
   "title": "Network Traffic Fifo",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_fifo_total{instance=~\"router:9731\",job=~\"router\"}[5m])",
     "legendFormat": "{{device}} - Receive fifo"
    },
    {
     "expr": "irate(node_network_transmit_fifo_total{instance=~\"router:9731\",job=~\"router\"}[5m])",
     "legendFormat": "{{device}} - Transmit fifo"
    }
   ]
  },
  {
   "title": "Network Traffic Colls",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short", "label": "Counter" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_colls_total{instance=~\"router:9731\",job=~\"router\"}[5m])",
     "legendFormat": "{{device}} - Transmit colls"
    }
   ]
  },
  {
   "title": "Network Traffic Carrier",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short", "label": "Counter" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_carrier_total{instance=~\"router:9731\",job=~\"router\"}[5m])",
     "legendFormat": "{{device}} - Statistic transmit_carrier"
    }
   ]
  },
  {
   "title": "NF Contrack",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "short", "label": "Entries" }
   ],
   "targets": [
    {
     "expr": "node_nf_conntrack_entries{instance=~\"router:9731\",job=~\"router\"}",
     "legendFormat": "NF conntrack entries"
    },
    {
     "expr": "node_nf_conntrack_entries_limit{instance=~\"router:9731\",job=~\"router\"}",
     "legendFormat": "NF conntrack limit"
    }
   ]
  },
  {
   "title": "Node Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Node Exporter Scrape Time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "s", "label": "Seconds" }
     ],
     "targets": [
      {
       "expr": "node_scrape_collector_duration_seconds{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "{{collector}} - Scrape duration"
      }
     ]
    },
    {
     "title": "Node Exporter Scrape Success",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 93 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "node_scrape_collector_success{instance=~\"router:9731\",job=~\"router\"}",
       "legendFormat": "{{collector}} - Scrape success"
      }
     ]
    }
   ]
  }
 ]
}